name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install toolchains
      run: |
        rustup toolchain install stable --component clippy --profile minimal
        rustup toolchain install nightly --component rustfmt --profile minimal
        rustup default stable

    - uses: Swatinem/rust-cache@v2

    - name: Install tombi
      uses: tombi-toml/setup-tombi@v1
      with:
        version: "0.10.0"

    - name: Rustfmt
      run: cargo +nightly fmt --all --check

    - name: Tombi format
      run: tombi format --check

    - name: Clippy
      run: cargo clippy --all-targets --all-features -- -D warnings

    - name: Rustdoc check
      run: cargo +nightly rustdoc -- -Z unstable-options --check

    - name: Test
      run: cargo test --verbose